---
- hosts: localhost
  connection: local
  vars:
    consul_bucket: consul_bucket
    aws_profile: aws_profile
  gather_facts: false
  tasks:
    - name: download server userdata template
      command: aws s3 cp s3://"${CONSUL_CONFIG_BUCKET}"/templates/server/userdata /tmp/server-userdata --profile {{ aws_profile }}
    - name: Add secret to server consul config file
      replace:
        path: /tmp/server-userdata
        regexp: "{_CONSUL_BUCKET_}"
        replace: "{{ consul_bucket }}"
    - name: upload server userdata script
      command: aws s3 cp /tmp/server-userdata s3://"${CONSUL_CONFIG_BUCKET}"/server/userdata --profile {{ aws_profile }}

    - name: download client userdata template
      command: aws s3 cp s3://"${CONSUL_CONFIG_BUCKET}"/templates/client/userdata /tmp/client-userdata --profile {{ aws_profile }}
    - name: Add secret to server consul config file
      replace:
        path: /tmp/client-userdata
        regexp: "{_CONSUL_BUCKET_}"
        replace: "{{ consul_bucket }}"
    - name: upload server userdata script
      command: aws s3 cp /tmp/client-userdata s3://"${CONSUL_CONFIG_BUCKET}"/client/userdata --profile {{ aws_profile }}